import { Data, IProductInput } from '@/types'
import { toSlug } from './utils'

const products: IProductInput[] = [
    {
      name: 'Xbox Series X',
      slug: toSlug('Xbox Series X'),
      category: 'consoles',
      images: ['/images/xbox.jpeg'],
      tags: ['new-arrival'],
      isPublished: true,
      price: 24999,
      listPrice: 54999,
      brand: 'Microsoft',
      avgRating: 4.8,
      numReviews: 120,
      ratingDistribution: [
        { rating: 1, count: 2 },
        { rating: 2, count: 5 },
        { rating: 3, count: 8 },
        { rating: 4, count: 30 },
        { rating: 5, count: 75 },
      ],
      numSales: 250,
      countInStock: 15,
      description: 'Experience true 4K gaming with the Xbox Series X, featuring a 1TB SSD, 12 teraflops of graphical power, and lightning-fast load times.',
      sizes: [],
      colors: ['Black'],
      reviews: [],
    },
    {
      name: 'Custom Gaming PC - Intel i9 RTX 4080',
      slug: toSlug('Custom Gaming PC - Intel i9 RTX 4080'),
      category: 'PC Builds',
      images: ['/images/pcf.jpeg'],
      tags: ['featured'],
      isPublished: true,
      price: 79999,
      listPrice: 120000,
      brand: 'Custom Build',
      avgRating: 4.9,
      numReviews: 85,
      ratingDistribution: [
        { rating: 1, count: 1 },
        { rating: 2, count: 2 },
        { rating: 3, count: 3 },
        { rating: 4, count: 20 },
        { rating: 5, count: 59 },
      ],
      numSales: 110,
      countInStock: 5,
      description: 'High-end gaming PC with Intel Core i9, RTX 4080, 32GB RAM, and 1TB NVMe SSD. Built for ultra settings and 4K gaming.',
      sizes: [],
      colors: ['Black', 'RGB'],
      reviews: [],
    },
    {
      name: 'Nintendo Switch (Neon Red/Blue)',
      slug: toSlug('Nintendo Switch Neon Red Blue'),
      category: 'consoles',
      images: ['/images/nini.jpeg'],
      tags: ['best-seller'],
      isPublished: true,
      price: 19999,
      listPrice: 34999,
      brand: 'Nintendo',
      avgRating: 4.7,
      numReviews: 250,
      ratingDistribution: [
        { rating: 1, count: 5 },
        { rating: 2, count: 10 },
        { rating: 3, count: 15 },
        { rating: 4, count: 50 },
        { rating: 5, count: 170 },
      ],
      numSales: 500,
      countInStock: 0,
      description: 'Play at home or on the go with the versatile Nintendo Switch. Features Neon Red and Blue Joy-Cons and access to a wide variety of games.',
      sizes: [],
      colors: ['Red', 'Blue', 'Black'],
      reviews: [],
    },
    {
      name: 'Sony PlayStation 5',
      slug: toSlug('Sony PlayStation 5'),
      category: 'consoles',
      images: ['/images/ps5.jpeg'],
      tags: ['featured', 'new-arrival'],
      isPublished: true,
      price: 49999,
      listPrice: 55000,
      brand: 'Sony',
      avgRating: 4.9,
      numReviews: 300,
      ratingDistribution: [
        { rating: 1, count: 3 },
        { rating: 2, count: 4 },
        { rating: 3, count: 8 },
        { rating: 4, count: 60 },
        { rating: 5, count: 225 },
      ],
      numSales: 600,
      countInStock: 12,
      description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio.',
      sizes: [],
      colors: ['White', 'Black'],
      reviews: [],
    },
  

      {
        name: "Marvel's Spider-Man",
        slug: toSlug("Marvel's Spider-Man"),
        category: 'games',
        images: ['/images/sp2.jpg','/images/spid.jpg'],
        tags: ['used', 'action'],
        isPublished: true,
        price: 950,
        listPrice: 1399,
        brand: 'Insomniac Games',
        avgRating: 4.7,
        numReviews: 84,
        ratingDistribution: [
          { rating: 1, count: 1 },
          { rating: 2, count: 3 },
          { rating: 3, count: 5 },
          { rating: 4, count: 20 },
          { rating: 5, count: 55 }
        ],
        numSales: 160,
        countInStock: 20,
        description: "Swing through New York City as Spider-Man in this high-adrenaline open-world action game.",
        sizes: [],
        colors: [],
        reviews: []
      },
      {
        name: "God of War: Ragnarök",
        slug: toSlug("God of War: Ragnarök"),
        category: 'games',
        images: ['/images/go2.jpg','/images/god.jpg'],
        tags: ['used', 'rpg'],
        isPublished: true,
        price: 1200,
        listPrice: 1999,
        brand: 'Santa Monica Studio',
        avgRating: 4.9,
        numReviews: 142,
        ratingDistribution: [
          { rating: 1, count: 0 },
          { rating: 2, count: 1 },
          { rating: 3, count: 2 },
          { rating: 4, count: 15 },
          { rating: 5, count: 124 }
        ],
        numSales: 280,
        countInStock: 30,
        description: "Join Kratos and Atreus in an epic mythological journey through the Norse realms in this critically acclaimed RPG.",
        sizes: [],
        colors: [],
        reviews: []
      },
      {
        name: "Red Dead Redemption II",
        slug: toSlug("Red Dead Redemption II"),
        category: 'games',
        images: ['/images/r2.jpg','/images/rdr.jpg'],
        tags: ['used', 'open-world'],
        isPublished: true,
        price: 899,
        listPrice: 1599,
        brand: 'Rockstar Games',
        avgRating: 4.8,
        numReviews: 96,
        ratingDistribution: [
          { rating: 1, count: 2 },
          { rating: 2, count: 2 },
          { rating: 3, count: 6 },
          { rating: 4, count: 25 },
          { rating: 5, count: 61 }
        ],
        numSales: 190,
        countInStock: 9,
        description: "Live the outlaw life in Rockstar's sprawling Western saga, featuring stunning visuals and gripping storytelling.",
        sizes: [],
        colors: [],
        reviews: []
      },
      {
        name: "The Last of Us Part II Remastered",
        slug: toSlug("The Last of Us Part II Remastered"),
        category: 'games',
        images: ['/images/lou.jpg'],
        tags: ['used', 'remastered'],
        isPublished: true,
        price: 1199,
        listPrice: 1799,
        brand: 'Naughty Dog',
        avgRating: 4.6,
        numReviews: 105,
        ratingDistribution: [
          { rating: 1, count: 3 },
          { rating: 2, count: 5 },
          { rating: 3, count: 8 },
          { rating: 4, count: 25 },
          { rating: 5, count: 64 }
        ],
        numSales: 220,
        countInStock: 12,
        description: "A beautifully remastered emotional rollercoaster, follow Ellie in a post-apocalyptic survival journey.",
        sizes: [],
        colors: [],
        reviews: []
      },
      {
        name: "PowerA Twin Charging Station for PS5 DualSense",
        slug: toSlug("PowerA Twin Charging Station for PS5 DualSense"),
        category: 'accessories',
        images: ['/images/ac1.jpg','/images/ac2.jpg','/images/ac3.jpg','/images/ac4.jpg','/images/ac5.jpg'],
        tags: ['new', 'officially licensed'],
        isPublished: true,
        price: 999,
        listPrice: 1799,
        brand: 'PowerA',
        avgRating: 4.6,
        numReviews: 26,
        ratingDistribution: [
          { rating: 1, count: 1 },
          { rating: 2, count: 2 },
          { rating: 3, count: 3 },
          { rating: 4, count: 8 },
          { rating: 5, count: 12 }
        ],
        numSales: 100,
        countInStock: 15,
        description: "A sleek and reliable dual charging dock for PS5 controllers, featuring fast charging, LED indicators, and an officially licensed vertical design.",
        sizes: [],
        colors: [],
        reviews: []
      }
      
    ];
       
  
  
const data: Data = {
  headerMenus: [
    {
      name: "Today's Deal",
      href: '/search?tag=todays-deal',
    },
    {
      name: 'New Arrivals',
      href: '/search?tag=new-arrival',
    },
    {
      name: 'Browsing History',
      href: '/#browsing-history',
    },
    {
      name: 'Customer Service',
      href: '/page/customer-service',
    },
    {
      name: 'About Us',
      href: '/page/about-us',
    },
    {
      name: 'Help',
      href: '/page/help',
    },
  ],
  carousels: [
   {
    title: 'Find Players Nearby You',
    buttonCaption: 'Find now',
    image: '/images/Untitled design (3).png',
    url: '/search?category=Search player',
    isPublished: true,
  },
  
  {
    title: 'Console Titles near you',
    buttonCaption: 'See Now',
    image: '/images/wp1.jpg',
    url: '/search?category=Titles',
    isPublished: true,
  },  
  {
    title: 'Best Selling Console',
    buttonCaption: 'Shop Now',
    image: '/images/Untitled design (4).png',
    url: '/product/sony-playstation-5',
    isPublished: true,
  },

  {
    title: 'Best accessories near you',
    buttonCaption: 'See More',
    image: '/images/wp2.png',
    url: '/product/powera-twin-charging-station-for-ps5-dualsense',
    isPublished: true,
  },
],
products
}

export default data